USE task_04;

SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE Royalties;
TRUNCATE TABLE Tracks_Artists;
TRUNCATE TABLE Tracks_Channels;
TRUNCATE TABLE Agreements;
TRUNCATE TABLE Tracks;
TRUNCATE TABLE Albums;
TRUNCATE TABLE Artists;
TRUNCATE TABLE DistributionChannels;
TRUNCATE TABLE Users;
TRUNCATE TABLE Genres;

SET FOREIGN_KEY_CHECKS = 1;
