vars:
    MYSQL_HOST: "{{ env_var('MYSQL_HOST') }}"
    MYSQL_DATABASE: "{{ env_var('MYSQL_DATABASE') }}"
    MYSQL_USER: "{{ env_var('MYSQL_USER') }}"
    MYSQL_PASSWORD: "{{ env_var('MYSQL_PASSWORD') }}"

name: 'dbt_04_task'
version: '1.0.0'
profile: 'dbt_04_task'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_04_task:
    example:
      +enabled: false

    raw:
      pre-hook:
        - "INSTALL mysql"
        - "LOAD mysql"
        - "ATTACH 'host={{ var('MYSQL_HOST') }} user={{ var('MYSQL_USER') }} password={{ var('MYSQL_PASSWORD') }} database={{ var('MYSQL_DATABASE') }}' AS mysqldb (TYPE MYSQL)"
      materialized: table

    staging:
      materialized: table
