version: 2

models:
  - name: stg_genres
    description: "Staging model for the Genres table"
    columns:
      - name: genre_id
        tests:
          - not_null
          - unique
      - name: genre_name
        tests:
          - not_null

  - name: stg_users
    description: "Staging model for the Users table"
    columns:
      - name: user_id
        tests:
          - not_null
          - unique
      - name: email
        tests:
          - not_null
          - unique
          - regex:
              pattern: '.*@.*'  # Check that email contains an '@' symbol
      - name: artist_id
        tests:
          - not_null

  - name: stg_artists
    description: "Staging model for the Artists table"
    columns:
      - name: artist_id
        tests:
          - not_null
          - unique
      - name: artist_name
        tests:
          - not_null

  - name: stg_albums
    description: "Staging model for the Albums table"
    columns:
      - name: album_id
        tests:
          - not_null
          - unique
      - name: album_title
        tests:
          - not_null
      - name: release_date
        tests:
          - not_null

  - name: stg_tracks
    description: "Staging model for the Tracks table"
    columns:
      - name: track_id
        tests:
          - not_null
          - unique
      - name: track_title
        tests:
          - not_null
      - name: track_status
        tests:
          - not_null
          - accepted_values:
              values: ['Pending', 'Active', 'Inactive']
