version: 2

models:
  - name: top_earning_tracks_and_artists
    description: "Top Earning Tracks and Artists by Royalties"
    columns:
      - name: track_title
        description: "Title of the track"
        tests:
          - not_null
      - name: artist_name
        description: "Name of the artist"
        tests:
          - not_null
      - name: total_royalties
        description: "Total royalties earned by the track and artist"
        tests:
          - not_null

  - name: top_active_tracks_and_artists_by_distribution
    description: "Top Active Tracks and Artists by Distribution Channels"
    columns:
      - name: artist_name
        description: "Name of the artist"
        tests:
          - not_null
      - name: active_tracks_count
        description: "Count of active tracks by the artist"
        tests:
          - not_null
      - name: total_channels
        description: "Total distribution channels where active tracks are available"
        tests:
          - not_null

  - name: top_distribution_channels_by_royalties
    description: "Top Distribution Channels by Total Royalties over the Last Year"
    columns:
      - name: channel_name
        description: "Name of the distribution channel"
        tests:
          - not_null
          - unique
      - name: total_royalties
        description: "Total royalties generated by the channel over the last year"
        tests:
          - not_null

  - name: top_artists_by_royalties_last_year
    description: "Top Artists by Total Royalties over the Last Year"
    columns:
      - name: artist_name
        description: "Name of the artist"
        tests:
          - not_null
      - name: total_royalties
        description: "Total royalties earned by the artist over the last year"
        tests:
          - not_null

  - name: top_genres_by_average_royalties_per_channel
    description: "Top Genres by Average Royalties for each Distribution Channel"
    columns:
      - name: channel_name
        description: "Name of the distribution channel"
        tests:
          - not_null
          - unique
      - name: genre_name
        description: "Name of the genre"
        tests:
          - not_null
      - name: avg_royalties_per_track
        description: "Average royalties per track for the genre on the distribution channel"
        tests:
          - not_null
